### ISSUE TITLE
Any chance to update this library for Nano RP2040 Connect ?

### ISSUE THREAD

**Issue by stefat** [arduino-libraries/Scheduler#16]
Any chance to update this library for Nano RP2040 Connect ?

**Comment by per1234** [comment]
Hi @stefat. I'm happy to tell you that the "**Arduino Mbed OS Nano Boards**" platform of the Arduino [Nano RP2040 Connect](https://store.arduino.cc/products/arduino-nano-rp2040-connect-with-headers) comes with its own variant of the Scheduler library.

So when you install support for the Nano RP2040 Connect in the Arduino IDE, you have already installed that Scheduler library. You can find a demonstration of its usage by doing this:

1. Select **Tools > Board > Arduino Mbed OS Nano Boards > Arduino Nano RP2040 Connect** from the Arduino IDE menus.
   (since this is a "platform bundled" library, the library is only accessible after you have selected a board of the "**Arduino Mbed OS Nano Boards**" platform)
1. Select **File > Examples > Scheduler > MultipleBlinks** from the Arduino IDE menus.
